<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap | Aura Home Office</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						margin: 0;
						padding: 40px 20px;
						background: #fcfcfc;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 40px;
						border-radius: 12px;
						box-shadow: 0 4px 20px rgba(0,0,0,0.05);
					}
					h1 {
						color: #1a1a1a;
						font-size: 28px;
						margin-bottom: 10px;
						font-weight: 800;
					}
					p {
						font-size: 14px;
						color: #666;
						margin-bottom: 30px;
						line-height: 1.6;
					}
					p a {
						color: #1a6b5a;
						text-decoration: none;
						font-weight: 600;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						padding: 15px 10px;
						border-bottom: 2px solid #f0f0f0;
						font-size: 12px;
						text-transform: uppercase;
						letter-spacing: 1px;
						color: #999;
					}
					td {
						padding: 15px 10px;
						border-bottom: 1px solid #f5f5f5;
						font-size: 14px;
					}
					tr:hover td {
						background: #f9f9f9;
					}
					a {
						color: #1a6b5a;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.priority-high { color: #1a6b5a; font-weight: bold; }
					.priority-low { color: #999; }
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p>
						This is a sitemap generated by <strong>Aura Home Office</strong> to allow search engines to discover this blog's content.<br/>
						You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.
					</p>
					
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
						<p>This sitemap index contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.</p>
						<table>
							<thead>
								<tr>
									<th>Sitemap URL</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td>
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), concat(' ', substring(sitemap:lastmod, 12, 5)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
						<p>This sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.</p>
						<table>
							<thead>
								<tr>
									<th>URL</th>
									<th>Priority</th>
									<th>Change Freq.</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td>
											<xsl:variable name="p" select="sitemap:priority"/>
											<span>
												<xsl:attribute name="class">
													<xsl:choose>
														<xsl:when test="$p &gt; 0.7">priority-high</xsl:when>
														<xsl:when test="$p &lt; 0.5">priority-low</xsl:when>
														<xsl:otherwise></xsl:otherwise>
													</xsl:choose>
												</xsl:attribute>
												<xsl:value-of select="concat(round($p * 100), '%')"/>
											</span>
										</td>
										<td>
											<xsl:value-of select="sitemap:changefreq"/>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), concat(' ', substring(sitemap:lastmod, 12, 5)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
